In [32]:
#Importing all the required Libraries
import pandas as pd
from sklearn.metrics import precision_score, accuracy_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

In [33]:
#Loading Dataset
iris_df = pd.read_csv("Iris.csv")
iris_df.info()
iris_df.sample(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
7,8,5.0,3.4,1.5,0.2,Iris-setosa
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
137,138,6.4,3.1,5.5,1.8,Iris-virginica
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
144,145,6.7,3.3,5.7,2.5,Iris-virginica
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
78,79,6.0,2.9,4.5,1.5,Iris-versicolor
21,22,5.1,3.7,1.5,0.4,Iris-setosa
118,119,7.7,2.6,6.9,2.3,Iris-virginica
76,77,6.8,2.8,4.8,1.4,Iris-versicolor

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
iris_df['Species'] = le.fit_transform(iris_df['Species'])

iris_df.sample(10)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
75    76            6.6           3.0            4.4           1.4        1
2      3            4.7           3.2            1.3           0.2        0
60    61            5.0           2.0            3.5           1.0        1
44    45            5.1           3.8            1.9           0.4        0
123  124            6.3           2.7            4.9           1.8        2
99   100            5.7           2.8            4.1           1.3        1
95    96            5.7           3.0            4.2           1.2        1
11    12            4.8           3.4            1.6           0.2        0
22    23            4.6           3.6            1.0           0.2        0
104  105            6.5           3.0            5.8           2.2        2

In [35]:
#Feature Extraction
X = iris_df.drop("Species", axis = 1)
y = iris_df["Species"]

In [36]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [37]:
#Model Trained through Logistic Regression
lr = LogisticRegression(max_iter = 1000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [38]:
#KNN 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors= 5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [40]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [43]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
models = {'Logistic Refresion': lr, 'KNN': knn , 'Naive Bayes': nb}

for name, model in models.items():
    y_pred = model.predict(X)
    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y, y_pred))
    print("cm:", confusion_matrix(y, y_pred))
    print("classification report:", classification_report(y, y_pred))

Logistic Refresion
Accuracy: 1.0
cm: [[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        50
           2       1.00      1.00      1.00        50

    accuracy                           1.00       150
   macro avg       1.00      1.00      1.00       150
weighted avg       1.00      1.00      1.00       150


KNN
Accuracy: 1.0
cm: [[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        50
           2       1.00      1.00      1.00        50

    accuracy                           1.00       150
   macro avg       1.00      1.00      1.00       150
weighted avg       1.00      1.00      1.00       150


Naive Bayes
Accuracy: 0.9933333333333333
cm: [[50  0  0]
 [ 0 50  0]
 [ 0  1 49]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.98      1.00      0.99        50
           2       1.00      0.98      0.99        50

    accuracy                           0.99       150
   macro avg       0.99      0.99      0.99       150
weighted avg       0.99      0.99      0.99       150